### PR TITLE
Update menu

### LINKED ISSUE #8: Update menu
Comments from @rartino:

Maybe make the subpage buttons vertical instead, similar to the hovering right-hand menu on the page https://tmd.gitlab-pages.liu.se or replace the OPTIMADE buttons in favor of a "back" button top left?

### PR DESCRIPTION
**Pull request by CasperWA**
Update menu according to the suggestion in #8.

Closes #8.

### CODE REVIEW

**Comment by rartino** [comment]
Is there any easy way to preview before merge?

**Comment by CasperWA** [comment]
Looks something like this:
image

Note, the arrow is fixed with regards to top and left.

**Comment by rartino** [comment]
Thanks for adding this; it is certainly an improvement so lets merge it.

**Comment by CasperWA** [comment]
For a wider viewport:
image

**Comment by CasperWA** [comment]
> Thanks for adding this; it is certainly an improvement so lets merge it.

Yeah, it's not pretty, but it's functional 😅

**Comment by CasperWA** [comment]
Optimally we'd have a logo we could put in instead of the OPTIMADE logo...

**Pull request merged**
