### PR TITLE
Add psi-k and MARVEL logos and sponsors section

### LINKED ISSUE #10: Add sponsor logos
Add logos for psi-k + MARVEL + LiU

### PR DESCRIPTION
**Pull request by CasperWA**
Fixes #10 

This adds a "Sponsor" section with the logos of the Psi-k Network and NCCR MARVEL, including links to their respective homepages.

Screendump:
image

### CODE REVIEW

**Comment by CasperWA** [comment]
Should we add Linköping University as well here? Or did you have some funds to be added @rartino?

**Comment by rartino** [comment]
Yes, please add the SeRC and LiU logos as well (attached; either the black or white LiU logo depending on what fits best - hmm - I guess it is the black)
serc
LiU_primary_white
LiU_primary_black

**Comment by CasperWA** [comment]
How about this then?
image

**Comment by CasperWA** [comment]
And maybe it should be "Funding" instead of sponsors?

**Comment by nicolamarzari** [comment]
Support?

Sent from a tiny keyboard... Contact info:
http://theossrv1.epfl.ch/Main/Contact

On 7 Jun 2021, at 23:06, Casper Welzel Andersen ***@***.***> wrote:

﻿

And maybe it should be "Funding" instead of sponsors?

**Comment by CasperWA** [comment]
> Support?

Support is good! I'll do that and then this is good to go. Right @rartino?

**Comment by rartino** [comment]
Thanks @CasperWA! I agree with 'Support'; the text and images are perfect, except that SeRC are particular about their capitalization and should be written like that, and not serc.

**Pull request merged**
